### Read all film
GET http://localhost:3000/films

### Read all pizzas with File variable

@baseUrl = http://localhost:3000
GET {{baseUrl}}/films/2
### Create a pizza


GET {{baseUrl}}/films/?minimum-duration=150



### create
POST {{baseUrl}}/films/create
Content-Type: application/json

{
       
        "title": "testKeterv",
        "director": "Christrettopher Nolan",
        "duration": 152,
        "budget":1222
        
}



### Delete a drink
DELETE {{baseUrl}}/films/2




